// GET  /api/public-roster                        -> public directory (no auth), safe field set only
// GET  /api/public-roster?action=self&token=X     -> one officer's own entry, by their private token
// POST /api/public-roster?action=selfUpdate       body { token, description?, imageBase64? }
//                                                  -> lets an officer update their OWN photo/bio only
//
// No login is involved for the self-service actions — knowing the token is
// the credential, the same trust model as the cadet invite links elsewhere
// in this app. Tokens are generated by admins and can be revoked/regenerated
// any time from the roster tab.

const { readDb, writeDb } = require('./_lib/db');
const { RANKS } = require('./_lib/ranks');

const MAX_IMAGE_BYTES = 2 * 1024 * 1024; // 2MB
const MAX_DESCRIPTION_LEN = 500;

function parseBody(req) {
  if (!req.body) return {};
  if (typeof req.body === 'string') {
    try { return JSON.parse(req.body); } catch (e) { return {}; }
  }
  return req.body;
}

function publicFields(r) {
  return {
    id: r.id,
    charname: r.charname,
    rank: r.rank,
    imageUrl: r.imageUrl || '',
    description: r.description || ''
  };
}

// Decodes a `data:image/png;base64,....` URL into a Buffer + extension,
// rejecting anything that isn't a plain PNG/JPEG or is too large.
function decodeImageDataUrl(dataUrl) {
  const match = /^data:(image\/(png|jpeg|jpg));base64,([A-Za-z0-9+/=]+)$/.exec(String(dataUrl || '').trim());
  if (!match) return { error: 'Only PNG or JPEG images are supported.' };
  const mime = match[1] === 'image/jpg' ? 'image/jpeg' : match[1];
  const ext = mime === 'image/png' ? 'png' : 'jpg';
  const buffer = Buffer.from(match[3], 'base64');
  if (buffer.length > MAX_IMAGE_BYTES) return { error: 'Image is too large — please keep it under 2MB.' };
  if (buffer.length === 0) return { error: 'That image looks empty — try a different file.' };
  return { buffer, mime, ext };
}

async function handleSelfGet(req, res) {
  const token = String(req.query.token || '').trim();
  if (!token) return res.status(400).json({ error: 'Missing token.' });
  try {
    const db = await readDb();
    const entry = db.roster.find((r) => r.selfToken === token);
    if (!entry) return res.status(404).json({ error: 'That link is invalid or has been revoked. Ask your admin for a new one.' });
    return res.status(200).json({ entry: publicFields(entry) });
  } catch (err) {
    console.error('public-roster self lookup error:', err);
    return res.status(500).json({ error: 'Could not reach the database.' });
  }
}

async function handleSelfUpdate(req, res) {
  const body = parseBody(req);
  const token = String(body.token || '').trim();
  if (!token) return res.status(400).json({ error: 'Missing token.' });

  try {
    const db = await readDb();
    const entry = db.roster.find((r) => r.selfToken === token);
    if (!entry) return res.status(404).json({ error: 'That link is invalid or has been revoked. Ask your admin for a new one.' });
    if (entry.status === 'discharged') return res.status(403).json({ error: 'This roster entry is no longer active.' });

    if (body.description !== undefined) {
      entry.description = String(body.description).trim().slice(0, MAX_DESCRIPTION_LEN);
    }

    if (body.imageBase64) {
      const decoded = decodeImageDataUrl(body.imageBase64);
      if (decoded.error) return res.status(400).json({ error: decoded.error });

      let put;
      try {
        ({ put } = require('@vercel/blob'));
      } catch (e) {
        return res.status(500).json({ error: 'Image storage isn\'t configured yet — ask your admin to enable Vercel Blob.' });
      }

      const filename = 'officers/' + entry.id + '-' + Date.now() + '.' + decoded.ext;
      const blob = await put(filename, decoded.buffer, { access: 'public', contentType: decoded.mime });
      entry.imageUrl = blob.url;
    }

    await writeDb(db);
    return res.status(200).json({ ok: true, entry: publicFields(entry) });
  } catch (err) {
    console.error('public-roster self update error:', err);
    return res.status(500).json({ error: 'Could not save your changes. Please try again.' });
  }
}

module.exports = async (req, res) => {
  const action = req.query.action;

  if (req.method === 'GET' && action === 'self') return handleSelfGet(req, res);
  if (req.method === 'POST' && action === 'selfUpdate') return handleSelfUpdate(req, res);

  if (req.method !== 'GET') return res.status(405).json({ error: 'Method not allowed.' });

  try {
    const db = await readDb();
    const roster = db.roster
      .filter((r) => r.status !== 'discharged')
      .sort((a, b) => RANKS.indexOf(b.rank) - RANKS.indexOf(a.rank) || a.charname.localeCompare(b.charname))
      .map(publicFields);

    res.status(200).json({ roster, ranks: RANKS });
  } catch (err) {
    console.error('public-roster error:', err);
    res.status(500).json({ error: 'Could not reach the database.' });
  }
};
